version: '2'
services:
  pdns:
    build: ./pdns/
    ports:
      - 127.0.0.1:53:53
      - 127.0.0.1:53:53/udp
      - 127.0.0.1:8081:8081
    environment:
      MYSQL_ROOT_PASSWORD: pizza_coke
    links:
      - mariadb
    depends_on:
      - mariadb
    entrypoint: /bin/bash /tmp/run.sh
    restart: always

  mariadb:
    image: mariadb
    volumes:
      - ./db_datadir:/var/lib/mysql
      - ./MariaDB:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: pizza_coke
    restart: always

  pdns_admin:
    build: ./pdns_admin/
    ports:
      - 127.0.0.01:9393:9393
    links:
      - mariadb
      - pdns
    environment:
      MYSQL_POWERDNS_USER_PASSWORD: takoyaki
    depends_on:
      - mariadb
    entrypoint: /work/PowerDNS-Admin/run.py
#    restart: always
